### ISSUE TITLE
More examples

### ISSUE THREAD

**Issue by holgersindbaek** [stripe/example-ios-backend#1]
I'm trying to implement Stripe in my iOS app, but I have a hard time finding any backend examples that are live. 

Specifically, I'm looking for an example that will let you:

1. Save a user
2. Retrieve a user
3. Make a payment

Preferably in Rails (but any language at this point would do). Any pointers?

**Comment by jflinter** [comment]
Hey Holger!

I'm sorry I didn't see this earlier; I wasn't watching this repository : /

I think you've figured this out by now, but for others reading this, I'd have a look at our [API reference](https://stripe.com/docs/api/ruby).

**Comment by holgersindbaek** [comment]
Haha ya. That's an old question. Not sure what I was thinking.
