### ISSUE TITLE
402 error on /customer/default_source using Stripe 2.4.0 and Sinatra 1.4.8

### ISSUE THREAD

**Issue by flexaddicted** [stripe/example-ios-backend#12]
I'm using Stripe 2.4.0 and Sinatra 1.4.8 for playing with the iOS example (see https://github.com/stripe/stripe-ios).

When the route `/customer/default_source` is invoked, I receive back the `402` error.

The sequence of calls is the following (using Charles Proxy):

1. `/customer?`
2. `/customer/sources`
3. `/customer?`
4. `/customer/default_source`

While call 2 returns the token `tok_1AAKzxHeD6mKz6pSbhD6ZKtQ`, call 4 returns `card_1AAKzxHeD6mKz6pSrY1VtDHH`.

Since they do not match, the error is returned back.

I've also noticed there is a mismatch between the documentation and the code provided. In particular, the documentation has the following code for routing the `default_source` route:

```
require "json"

post "/customer/default_source" do
  begin
    customer_id = "..." # Load the Stripe Customer ID for your logged in user
    customer = Stripe::Customer.retrieve(customer_id)
    customer.default_source = params[:default_source]
    customer.save
    status 200
  rescue Stripe::StripeError => e
    status 402
    return "Error retrieving customer: #{e.message}"
  end
end
```

While the code in the example is:

```
post '/customer/default_source' do
  authenticate!
  source = params[:source]

  # Sets the customer's default source
  begin
    @customer.default_source = source
    @customer.save
  rescue Stripe::StripeError => e
    status 402
    return "Error selecting default source: #{e.message}"
  end

  status 200
  return "Successfully selected default source."
end
```

In the former `params[:default_source]` is used while in the latter `params[:source]` is adopted.

Any clue? Do I need to update the iOS Stripe lib? Using the code as is (with gem files dependencies in the `Gemfile`) it works as expected.

Thanks, Lorenzo

**Comment by flexaddicted** [comment]
I found the problem.

I'm using Ruby 2.4.0 where `OpenSSL::Cipher::Cipher` has been deprecated.
Removing that line and replacing it with `enable :sessions` it works as expected. It should be better to use `OpenSSL::Cipher` instead.

Are you able to provide a clarifications on the mismatch between the documentation and the code provided? Should we use `:source` or `:default_source`?

Thanks, Lorenzo

**Comment by joeydong-stripe** [comment]
Thanks for posting the question and sorry we didn't get back to you sooner @flexaddicted
