### ISSUE TITLE
Error 500 when trying to charge from Android App - NoMethodError - undefined method indifferent_params

### ISSUE THREAD

**Issue by mouss-delta** [stripe/example-ios-backend#29]
I have deployed the sample backend on heroku but when I charge I get an error 500 : 

> 2018-06-11T08:39:43.833591+00:00 heroku[router]: at=info method=POST path="/charge" host=myapp.herokuapp.com request_id=f4b4e2b2-0000-1111-9999-e9542b146e2b fwd="XX.YYY.ZZ.00" dyno=web.1 connect=0ms service=716ms status=500 bytes=685 protocol=https
> 2018-06-11T08:39:43.834101+00:00 app[web.1]: 2018-06-11 08:39:43 - NoMethodError - undefined method indifferent_params for #Sinatra::Application:0x00000000023e0970:
> 2018-06-11T08:39:43.834111+00:00 app[web.1]: 	web.rb:45:in block in main
> 2018-06-11T08:39:43.834114+00:00 app[web.1]: 	/app/vendor/bundle/ruby/2.5.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1634:in `call'

**Comment by mouss-delta** [comment]
I have just created a pull request that fixed the issue for me on my heroku deployed app

**Comment by joeydong-stripe** [comment]
Ah nice! I'll take a look.
