### ISSUE TITLE
Email receipt and customer description 

### ISSUE THREAD

**Issue by podycust** [stripe/example-ios-backend#33]
am New to ruby etc just wonder if it’s possible for the backend to be passed a description for customer such as name and not have it hard coded and if it’s possi to automatically send a email receipt?

**Comment by joeydong-stripe** [comment]
Hi @podycust,

Please only file issues here that you believe represent actual bugs or feature requests for the example-ios-backend.

If you're having general trouble with your Stripe integration, please reach out to support using the form at https://support.stripe.com/ (preferred) or via email to support@stripe.com.

Regarding your particular question, I believe it is possible depending on the payment method you are accepting. Email support and they will work with you on specific to your situation.
