### ISSUE TITLE
Heroku deployment error

### ISSUE THREAD

**Issue by andreatoso** [stripe/example-ios-backend#40]
Trying to deploy the example app on Heroku results in an error during the "Build app" step. This is the log: 
>-----> Ruby app detected
-----> Compiling Ruby/Rack
-----> Using Ruby version: ruby-2.5.0
-----> Installing dependencies using bundler 1.15.2
       Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
       Warning: the running version of Bundler (1.15.2) is older than the version that created the lockfile (1.16.1). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
       Fetching gem metadata from https://rubygems.org/.......
       Fetching version metadata from https://rubygems.org/..
       Fetching dependency metadata from https://rubygems.org/.
       Could not find multipart-post-2.0.0 in any of the sources
       Bundler Output: Warning: the running version of Bundler (1.15.2) is older than the version that created the lockfile (1.16.1). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
       Fetching gem metadata from https://rubygems.org/.......
       Fetching version metadata from https://rubygems.org/..
       Fetching dependency metadata from https://rubygems.org/.
       Could not find multipart-post-2.0.0 in any of the sources
 !
 !     Failed to install gems via Bundler.
 !
 !     Push rejected, failed to compile Ruby app.
 !     Push failed>

**Comment by danj-stripe** [comment]
Hi @andreatoso,

I'm unable to reproduce this today. Can you try again and see if it's working?

I think its possible you hit the 17 minute window yesterday in which rubygems was having problems:
https://status.rubygems.org/
<img width="857" alt="screen shot 2019-01-02 at 10 59 23 am" src="https://user-images.githubusercontent.com/30532866/50607287-81080c80-0e7d-11e9-824e-3c7b63fc8617.png">

Deploying via the Deploy to Heroku button in our repo shows the same Ruby/bundler/multipart-post versions and output that you've included, but it succeeds for me:

    -----> Ruby app detected
    -----> Compiling Ruby/Rack
    -----> Using Ruby version: ruby-2.5.0
    -----> Installing dependencies using bundler 1.15.2
           Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
           Warning: the running version of Bundler (1.15.2) is older than the version that created the lockfile (1.16.1). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
           Fetching gem metadata from https://rubygems.org/........
           Fetching version metadata from https://rubygems.org/.
           Using bundler 1.15.2
           Fetching dotenv 2.2.1
           Fetching rack 2.0.6
           Fetching multipart-post 2.0.0
           Installing multipart-post 2.0.0
           Installing dotenv 2.2.1
           Installing rack 2.0.6
           Using json 2.1.0
           Fetching mustermann 1.0.3
           Fetching tilt 2.0.8
           Installing mustermann 1.0.3
           Installing tilt 2.0.8
           Fetching faraday 0.15.3
           Installing faraday 0.15.3
           Fetching stripe 3.17.0
           Installing stripe 3.17.0
           Fetching encrypted_cookie 0.0.5
           Fetching rack-protection 2.0.2
           Installing encrypted_cookie 0.0.5
           Installing rack-protection 2.0.2
           Fetching sinatra 2.0.2
           Installing sinatra 2.0.2
           Bundle complete! 5 Gemfile dependencies, 12 gems now installed.
           Gems in the groups development and test were not installed.
           Bundled gems are installed into ./vendor/bundle.
           Bundle completed (3.28s)
           Cleaning up the bundler cache.
           Warning: the running version of Bundler (1.15.2) is older than the version that created the lockfile (1.16.1). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
    -----> Detecting rake tasks
    -----> Discovering process types
           Procfile declares types     -> web
           Default types for buildpack -> console, rake
    -----> Compressing...
           Done: 20.2M
    -----> Launching...
           Released v5
           https://fierce-sea-21204.herokuapp.com/ deployed to Heroku
