### ISSUE TITLE
charge and  charge_card endpoint not working with swift. 

### ISSUE THREAD

**Issue by mhegdeopteamix** [stripe/example-ios-backend#8]
I have deployed as per the instructions.  I have used custom stripe integration. **/charge** endpoint not working in both swift and objective C. But charge_card endpoint only working in objective C.

I have used STPAddCardViewController. The token is successfully generated. 

          let paymentURL = URLBuilder.chargeURL() //https://stripepaymentdemo.herokuapp.com/charge
           print("payment url is \(paymentURL)")
        //var urlRequest = URLRequest(url: paymentURL)
        Alamofire.request(paymentURL, method: .post,
                    parameters: self.paymentInfo,
                    encoding: JSONEncoding.default, headers: [:]).validate().responseJSON { (response) in
            
            switch(response.result) {
            case .success(_):
                if let data = response.result.value {
                    print(response.result.value ?? "data is nil")
                    self.completionHadler(data, nil)
                }
                break
                
            case .failure(_):
                print(response.result.error ?? "error is nil")
                self.completionHadler(nil, response.result.error)
                break
                
            }
        }
      // Payment Info:
      let params: [String: Any] = [
            "stripe_token": token.tokenId ,
            "amount": 4000
        ]

**Comment by bg-stripe** [comment]
@mhegdeopteamix This backend is intended to work with the sample apps that ship with the SDK. The endpoints here are for demonstration purposes only – you should use your own backend in your own app.

Note that we've changed the name of the `charge_card` endpoint – it is now `create_charge`, and takes a `source` parameter.
